#pragma once

// Auto-generated header for best FFT indices
// Generated by Stage 2 in Python

const int FFT_BEST_INDEX_AG_X = 1;
const int FFT_BEST_INDEX_AG_Y = 1;
const int FFT_BEST_INDEX_AG_Z = 1;
const int FFT_BEST_INDEX_G_X  = 1;
const int FFT_BEST_INDEX_G_Y  = 1;
const int FFT_BEST_INDEX_G_Z  = 1;

// Number of FFT best indices available
const int NUM_FFT_BEST_INDEX = 6;
